# coding: utf-8

name: publish-lefaso-scraper

run-name: trigged by ${{github.actor}}

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependacies
        run: |
          sudo apt-get update
          sudo curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.in-project true
          poetry install
      
      - name: Config Poetry
        run: |
          export PATH=".venv/bin:$PATH"
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Build Package
        run: |
          poetry build
      
      - name: Publish Package
        run: |
          poetry publish
